### ISSUE TITLE
Zip doesn't have [Content_Types].xml

### ISSUE THREAD

**Issue by mallim** [ngs-doo/TemplaterExamples#10]
How can I fix this issue? I had used a docx file converted from doc via WPS Writer.

java.io.FileNotFoundException: Zip doesn't have [Content_Types].xml

	at hr.ngs.templater.cc.<init>(Unknown Source)
	at hr.ngs.templater.rn.<init>(Unknown Source)
	at hr.ngs.templater.uy.<init>(Unknown Source)
	at hr.ngs.templater.ab.<init>(Unknown Source)
	at hr.ngs.templater.ap.a(Unknown Source)
	at hr.ngs.templater.al.<init>(Unknown Source)
	at hr.ngs.templater.a.open(Unknown Source)

**Comment by zapov** [comment]
That file is required within docx. To it seems the converter is not creating valid docx files. You can try to hack around it by adding some generic content file, eg copy it from another valid docx file.

**Comment by mallim** [comment]
thanks for the advice. is the file generated bumy wps office is.not compatible.
